word_list2 = [
"Afghanistan",
"Andorra la Vella",
"Buenos Aires",
"Bosnia and Herzegovina",
"Bandar Seri Begawan",
"Burkina Faso",
"Ouagadougou",
"Central African Republic",
"Democratic Republic of the Congo",
"Republic of the Congo",
"Brazzaville",
"Czech Republic",
"Dominican Republic",
"Santo Domingo",
"San Salvador",
"Equatorial Guinea",
"Guatemala City",
"Guinea-Bissau",
"Tegucigalpa",
"South Tarawa",
"Liechtenstein", 
"Antananarivo",
"Kuala Lumpur",
"Marshall Islands",
"Ulaanbaatar",
"Yaren District",
"Netherlands",
"Papua New Guinea", 
"Port Moresby",
"Philippines",
"Saint Kitts and Nevis", 
"Saint Vincent and the Grenadines",
"Saudi Arabia",
"Sierra Leone",
"Solomon Islands",
"South Africa",
"Switzerland", 
"Trinidad and Tobago", 
"Port of Spain",
"Turkmenistan",
"United Arab Emirates",
"United Kingdom", 
"United States of America"]